[package]
name = "Launcher"
version = "0.2.0"
edition = "2021"

[dependencies]
byteorder = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net"] }

[profile.release]
strip = "debuginfo"
opt-level = "z"
lto = true
