name: Release

on:
  push:
    tags:
      - "**"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Dotnet Restore
        run: dotnet restore
      - name: Build
        run: .\Utils\build.ps1
      - name: Create Github Release
        run: gh release create ${{ github.ref_name }} './Utils/Hurl_Installer.exe' --title "${{ github.ref_name }}" --draft --latest --verify-tag --notes-from-tag
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Hurl_Installer
          path: ./Utils/Hurl_Installer.exe
