name: Release

on:
  push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: .\Utils\build.ps1
    # - name: Release
    #   uses: softprops/action-gh-release@v0.1.13
    #   with:
    #     draft: true
    #     files: build_installer/LenovoLegionToolkitSetup.exe
    #     fail_on_unmatched_files: true
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Hurl_Installer
        path: ./Utils/Hurl_Installer.exe
